spring:
  application:
    name: License Write Side Application

  datasource:
    url: jdbc:mysql://db:3306/license
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
     hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
