version: "3"

services:
  rabbitmq:
    image: smebberson/alpine-rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - back-tier

  db:
    image: imega/mysql
    container_name: db
    ports:
      - "3306:3306"
    networks:
      - back-tier

networks:
  front-tier:
  back-tier: